# Generated by Django 5.2 on 2025-05-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alumniprofile_careerupdate_event_mentorshiprequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
