# Generated by Django 5.2 on 2025-05-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_alumniprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
